export const FRUITS_AND_VEGETABLES = [
  { id: 1, name: 'Almonds' },
  { id: 2, name: 'Apple' },
  { id: 3, name: 'Apricot' },
  { id: 4, name: 'Artichoke' },
  { id: 5, name: 'Asparagus' },
  { id: 6, name: 'Aubergine (Eggplant)' },
  { id: 7, name: 'Avocado' },
  { id: 8, name: 'Banana' },
  { id: 9, name: 'Beetroot' },
  { id: 10, name: 'Black Beans' },
  { id: 11, name: 'Blackberry' },
  { id: 12, name: 'Blueberry' },
  { id: 13, name: 'Bok Choy' },
  { id: 14, name: 'Brazil Nuts' },
  { id: 15, name: 'Broccoli' },
  { id: 16, name: 'Brussels Sprouts' },
  { id: 17, name: 'Butternut Squash' },
  { id: 18, name: 'Cabbage' },
  { id: 19, name: 'Cantaloupe' },
  { id: 20, name: 'Carrot' },
  { id: 21, name: 'Cashews' },
  { id: 22, name: 'Cauliflower' },
  { id: 23, name: 'Celery' },
  { id: 24, name: 'Cherry' },
  { id: 25, name: 'Chia Seeds' },
  { id: 26, name: 'Chickpeas' },
  { id: 27, name: 'Chicory' },
  { id: 28, name: 'Clementine' },
  { id: 29, name: 'Coconut' },
  { id: 30, name: 'Collard Greens' },
  { id: 31, name: 'Corn' },
  { id: 32, name: 'Courgette (Zucchini)' },
  { id: 33, name: 'Cranberry' },
  { id: 34, name: 'Cucumber' },
  { id: 35, name: 'Date' },
  { id: 36, name: 'Dragonfruit' },
  { id: 37, name: 'Edamame (Soybeans)' },
  { id: 38, name: 'Endive' },
  { id: 39, name: 'Fennel' },
  { id: 40, name: 'Fig' },
  { id: 41, name: 'Flaxseed' },
  { id: 42, name: 'Garlic' },
  { id: 43, name: 'Ginger' },
  { id: 44, name: 'Goji Berry' },
  { id: 45, name: 'Grape' },
  { id: 46, name: 'Grapefruit' },
  { id: 47, name: 'Green Bean' },
  { id: 48, name: 'Guava' },
  { id: 49, name: 'Hazelnuts' },
  { id: 50, name: 'Hemp Seeds' },
  { id: 51, name: 'Honeydew Melon' },
  { id: 52, name: 'Jalapeño' },
  { id: 53, name: 'Jicama' },
  { id: 54, name: 'Kale' },
  { id: 55, name: 'Kidney Beans' },
  { id: 56, name: 'Kimchi' },
  { id: 57, name: 'Kiwi' },
  { id: 58, name: 'Kohlrabi' },
  { id: 59, name: 'Leek' },
  { id: 60, name: 'Lemon' },
  { id: 61, name: 'Lentils' },
  { id: 62, name: 'Lettuce' },
  { id: 63, name: 'Lime' },
  { id: 64, name: 'Lychee' },
  { id: 65, name: 'Mango' },
  { id: 66, name: 'Mushroom' },
  { id: 67, name: 'Nectarine' },
  { id: 68, name: 'Okra' },
  { id: 69, name: 'Olive' },
  { id: 70, name: 'Onion' },
  { id: 71, name: 'Orange' },
  { id: 72, name: 'Papaya' },
  { id: 73, name: 'Parsnip' },
  { id: 74, name: 'Passion Fruit' },
  { id: 75, name: 'Pea' },
  { id: 76, name: 'Peach' },
  { id: 77, name: 'Peanuts' },
  { id: 78, name: 'Pear' },
  { id: 79, name: 'Pecans' },
  { id: 80, name: 'Pepper (Bell Pepper)' },
  { id: 81, name: 'Persimmon (Sharon Fruit)' },
  { id: 82, name: 'Pineapple' },
  { id: 83, name: 'Pinto Beans' },
  { id: 84, name: 'Pistachios' },
  { id: 85, name: 'Plum' },
  { id: 86, name: 'Pomegranate' },
  { id: 87, name: 'Potato' },
  { id: 88, name: 'Pumpkin' },
  { id: 89, name: 'Pumpkin Seeds' },
  { id: 90, name: 'Radicchio' },
  { id: 91, name: 'Radish' },
  { id: 92, name: 'Raspberry' },
  { id: 93, name: 'Rhubarb' },
  { id: 94, name: 'Rocket (Arugula)' },
  { id: 95, name: 'Sauerkraut' },
  { id: 96, name: 'Seaweed' },
  { id: 97, name: 'Shallot' },
  { id: 98, name: 'Spinach' },
  { id: 99, name: 'Spring Onion (Scallion)' },
  { id: 100, name: 'Squash' },
  { id: 101, name: 'Starfruit' },
  { id: 102, name: 'Strawberry' },
  { id: 103, name: 'Sunflower Seeds' },
  { id: 104, name: 'Swede' },
  { id: 105, name: 'Sweet Potato' },
  { id: 106, name: 'Swiss Chard' },
  { id: 107, name: 'Tangerine' },
  { id: 108, name: 'Tomato' },
  { id: 109, name: 'Turnip' },
  { id: 110, name: 'Walnuts' },
  { id: 111, name: 'Watercress' },
  { id: 112, name: 'Watermelon' },
  { id: 113, name: 'Yam' },
];